export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const TOGGLE_PRODUCT_TYPE = "TOGGLE_PRODUCT_TYPE";
export const SEARCH_PRODUCT_BY_NAME = "SEARCH_PRODUCT_BY_NAME";
export const SEARCH_PRODUCT_BY_ID = "SEARCH_PRODUCT_BY_ID";
export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const ORDER_NAME = "ORDER_NAME";
export const ORDER_PRECIO= "ORDER_PRECIO";

