export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const TOGGLE_PRODUCT_TYPE = "TOGGLE_PRODUCT_TYPE";
export const SEARCH_PRODUCT_BY_NAME = "SEARCH_PRODUCT_BY_NAME";
export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";
